[package]
name = "neo64fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
display-info = "0.5.7"
image = "0.25.9"
libc = "0.2.179"
objc2 = "0.6.3"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
plist = "1.8.0"
sysinfo = "0.37.2"
base64 = "0.22.1"
